#!/usr/bin/env node
// Flattens src/*.js + protocol.js into a single, dependency-free script:
// dist/experiment.js. That's the file to paste into the Lookit
// builder as the study's protocol generator.
//
// Lookit's protocol-generator field expects the ENTIRE pasted script to
// be one `function generateProtocol(child, pastSessions) { ... }`
// declaration - no top-level const/function statements beside it (their
// own docs' examples nest helper functions inside generateProtocol, not
// next to it). So every src/*.js top-level binding and protocol.js's
// getChildId helper get nested inside the generated generateProtocol
// body, followed by protocol.js's own generateProtocol body statements.
//
// Not a real bundler - just strips the require()/module.exports lines
// that only exist for local Node testing, then concatenates in
// dependency order, wrapped in the single function shell. Re-run this
// after any src/*.js or protocol.js edit.

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const SRC_FILES = ['config.js', 'pairs.js', 'randomization.js', 'frames.js', 'text.js'];
const OUT_FILE = path.join(ROOT, 'dist', 'experiment.js');
const GENERATE_PROTOCOL_SIGNATURE = 'function generateProtocol(child, pastSessions) {';

function stripModuleSystem(code) {
  return code
    .replace(/^const\s*\{[^}]*\}\s*=\s*require\([^)]*\);\s*$/gm, '')
    .replace(/^const\s+\w+\s*=\s*require\([^)]*\);\s*$/gm, '')
    .replace(/^module\.exports\s*=\s*\{[\s\S]*?\};\s*$/m, '');
}

function readSrc(file) {
  return fs.readFileSync(path.join(ROOT, 'src', file), 'utf8');
}

// Splits protocol.js's stripped source into everything before
// generateProtocol (leading comments + the getChildId helper) and the
// statements inside generateProtocol's own body, by counting braces from
// its opening `{` - protocol.js has no braces inside string literals, so
// this is safe without a real parser.
function extractGenerateProtocolBody(code) {
  const startIdx = code.indexOf(GENERATE_PROTOCOL_SIGNATURE);
  if (startIdx === -1) {
    throw new Error('Could not find generateProtocol declaration in protocol.js');
  }
  const bodyStart = startIdx + GENERATE_PROTOCOL_SIGNATURE.length;
  let depth = 1;
  let i = bodyStart;
  for (; i < code.length && depth > 0; i++) {
    if (code[i] === '{') depth++;
    else if (code[i] === '}') depth--;
  }
  if (depth !== 0) {
    throw new Error('Unbalanced braces while extracting generateProtocol body from protocol.js');
  }
  return {
    helpers: code.slice(0, startIdx).trim(),
    mainBody: code.slice(bodyStart, i - 1).trim(),
  };
}

let inner = '';

for (const file of SRC_FILES) {
  inner += `// ---- src/${file} ----\n`;
  inner += stripModuleSystem(readSrc(file)).trim();
  inner += '\n\n';
}

const { helpers, mainBody } = extractGenerateProtocolBody(
  stripModuleSystem(fs.readFileSync(path.join(ROOT, 'protocol.js'), 'utf8'))
);
inner += '// ---- protocol.js ----\n';
inner += helpers + '\n\n';
inner += mainBody + '\n';

let body = '// AUTO-GENERATED by scripts/build.js - do not edit by hand.\n';
body += '// Edit src/*.js and protocol.js, then re-run `node scripts/build.js`.\n\n';
body += `${GENERATE_PROTOCOL_SIGNATURE}\n`;
body += inner;
body += '}\n';

fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
fs.writeFileSync(OUT_FILE, body);
console.log(`Wrote ${OUT_FILE}`);
