#!/usr/bin/env node
// Flattens src/*.js + protocol.js into a single, dependency-free script:
// dist/protocol.generated.js. That's the file to paste into the Lookit
// builder as the study's protocol generator - Lookit loads one script and
// expects a bare `generateProtocol(child, pastSessions)` function, the
// same shape placepath-behavioral's scripts/experiment.js uses, with no
// require()/module system.
//
// Not a real bundler - just strips the require()/module.exports lines that
// only exist for local Node testing, then concatenates in dependency
// order. Re-run this after any src/*.js or protocol.js edit.

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const SRC_FILES = ['config.js', 'pairs.js', 'randomization.js', 'frames.js', 'text.js'];
const OUT_FILE = path.join(ROOT, 'dist', 'protocol.generated.js');

function stripModuleSystem(code) {
  return code
    .replace(/^const\s*\{[^}]*\}\s*=\s*require\([^)]*\);\s*$/gm, '')
    .replace(/^const\s+\w+\s*=\s*require\([^)]*\);\s*$/gm, '')
    .replace(/^module\.exports\s*=\s*\{[\s\S]*?\};\s*$/m, '');
}

function readSrc(file) {
  return fs.readFileSync(path.join(ROOT, 'src', file), 'utf8');
}

let body = '// AUTO-GENERATED by scripts/build.js - do not edit by hand.\n';
body += '// Edit src/*.js and protocol.js, then re-run `node scripts/build.js`.\n\n';

for (const file of SRC_FILES) {
  body += `// ---- src/${file} ----\n`;
  body += stripModuleSystem(readSrc(file)).trim();
  body += '\n\n';
}

body += '// ---- protocol.js ----\n';
body += stripModuleSystem(fs.readFileSync(path.join(ROOT, 'protocol.js'), 'utf8')).trim();
body += '\n';

fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
fs.writeFileSync(OUT_FILE, body);
console.log(`Wrote ${OUT_FILE}`);
